name: integration-test
on:
  push:

jobs:

  basic-ubuntu-20-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: next-js-boilerplate
          build: npx cypress info
