name: integration-test
on:
  push:
  pull_request:
jobs:

  basic-ubuntu-20-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/v10/basic
          build: npx cypress info